import inquirer from 'inquirer'
import chalk from 'chalk'
import ora from 'ora'
import fs from 'node:fs/promises'
import path from 'node:path'
import { SUPPORTED_MODELS } from '@trooper/core'

export async function init() {
  console.log(chalk.cyan('  Let\'s get Trooper set up.\n'))

  const { provider } = await inquirer.prompt([
    {
      type: 'list',
      name: 'provider',
      message: 'Which AI model do you want to use?',
      choices: Object.entries(SUPPORTED_MODELS).map(([key, val]) => ({
        name: `${val.label}${!val.requiresKey ? chalk.green(' (free, no API key)') : ''}`,
        value: key,
      })),
    },
  ])

  const providerConfig = SUPPORTED_MODELS[provider]

  const { model } = await inquirer.prompt([
    {
      type: 'list',
      name: 'model',
      message: 'Which model?',
      choices: providerConfig.models,
    },
  ])

  let apiKey = ''
  if (providerConfig.requiresKey) {
    const result = await inquirer.prompt([
      {
        type: 'password',
        name: 'apiKey',
        message: `${providerConfig.label} API key:`,
        validate: (v: string) => v.length > 0 || 'API key is required',
      },
    ])
    apiKey = result.apiKey
  }

  const { githubToken } = await inquirer.prompt([
    {
      type: 'password',
      name: 'githubToken',
      message: 'GitHub personal access token (needs repo + pull_request scopes):',
      validate: (v: string) => v.length > 0 || 'GitHub token is required',
    },
  ])

  const { repoOwner, repoName } = await inquirer.prompt([
    {
      type: 'input',
      name: 'repoOwner',
      message: 'GitHub repo owner (e.g. acme-corp):',
      validate: (v: string) => v.length > 0 || 'Required',
    },
    {
      type: 'input',
      name: 'repoName',
      message: 'GitHub repo name (e.g. my-app):',
      validate: (v: string) => v.length > 0 || 'Required',
    },
  ])

  const { port } = await inquirer.prompt([
    {
      type: 'input',
      name: 'port',
      message: 'Port to run on:',
      default: '3000',
    },
  ])

  const spinner = ora('Writing config...').start()

  const envContent = [
    `# Trooper config — generated by npx usetrooper`,
    `TROOPER_MODEL_PROVIDER=${provider}`,
    `TROOPER_MODEL_NAME=${model}`,
    apiKey ? `TROOPER_API_KEY=${apiKey}` : '',
    `TROOPER_GITHUB_TOKEN=${githubToken}`,
    `TROOPER_REPO_OWNER=${repoOwner}`,
    `TROOPER_REPO_NAME=${repoName}`,
    `NEXT_PUBLIC_REPO_OWNER=${repoOwner}`,
    `NEXT_PUBLIC_REPO_NAME=${repoName}`,
    `PORT=${port}`,
    `DATABASE_URL=file:./trooper.db`,
  ]
    .filter(Boolean)
    .join('\n')

  await fs.writeFile(path.join(process.cwd(), '.env'), envContent, 'utf-8')

  spinner.succeed('Config written to .env')

  const migrateSpinner = ora('Setting up database...').start()
  try {
    const { execSync } = await import('node:child_process')
    execSync('npx prisma migrate deploy', {
      stdio: 'pipe',
      env: { ...process.env, DATABASE_URL: 'file:./trooper.db' },
    })
    migrateSpinner.succeed('Database ready')
  } catch {
    migrateSpinner.warn('Could not run migrations automatically — run: npx prisma migrate deploy')
  }

  console.log(chalk.green('\n  Trooper is ready!\n'))
  console.log(`  Run ${chalk.bold('npx usetrooper start')} to launch the dashboard`)
  console.log(`  Run ${chalk.bold('npx usetrooper worker')} in a second terminal to start the agent\n`)
  console.log(`  Or connect a feedback source:`)
  console.log(`    GitHub Issues  →  add webhook: POST /api/ingest/github`)
  console.log(`    Custom         →  POST /api/ingest/webhook\n`)
}
